version: "3.3"
services:
  db:
    image: 'redis:4-alpine'
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - welland-canal-network  
  api:
    build: ./api
    ports:
      - '8080:8080'
    links:
      - db
    env_file: secret.env
    networks:
      - welland-canal-network  
networks:
  welland-canal-network:
    driver: bridge